baseURL = 'https://jyukki.com'
languageCode = 'ko-kr'
title = "jyukki's Blog"
theme = 'PaperMod'

# 성능 최적화 설정
enableInlineShortcodes = true
enableRobotsTXT = true
enableGitInfo = false
# taxonomy와 terms 활성화 (태그 기능을 위해)
# disableKinds = ["taxonomy", "term"]

# Taxonomy 설정 (태그 및 카테고리 활성화)
[taxonomies]
  tag = 'tags'
  category = 'categories'

# 빌드 성능 최적화
timeout = "30s"
enableEmoji = false
canonifyURLs = true
relativeURLs = false

# 이미지 처리 최적화
[imaging]
  resampleFilter = "CatmullRom"
  quality = 85
  hint = "photo"

[params]
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  ShowToc = true
  TocOpen = true
  showTagsOnHome = true
  
  # 성능 최적화 관련 설정
  enableSearch = true
  disableSearch = false
  env = "production"

  # Giscus 댓글 시스템 설정 (Phase 3.2)
  [params.giscus]
    repo = "jyukki97/study-blog"  # GitHub 저장소 (사용자명/저장소명)
    repoID = "R_kgDOO6eCyQ"  # GitHub 저장소 ID (Giscus 설정에서 생성)
    category = "General"  # Discussion 카테고리
    categoryID = "DIC_kwDOO6eCyc4CrZf3"  # 카테고리 ID (Giscus 설정에서 생성)
    mapping = "pathname"  # URL과 Discussion 매핑 방식
    strict = "0"  # 엄격한 매핑 (0=비활성화, 1=활성화)
    reactionsEnabled = "1"  # 반응 버튼 활성화
    emitMetadata = "0"  # 메타데이터 전송
    inputPosition = "bottom"  # 댓글 입력창 위치 (top/bottom)
    theme = "preferred_color_scheme"  # 테마 (light/dark/preferred_color_scheme)
    lang = "ko"  # 언어 설정

  # Google Analytics 4 설정 (Phase 3.3)
  [params.analytics]
    [params.analytics.google]
      GA_MEASUREMENT_ID = "G-4BH0XLL42M"  # Google Analytics 4 측정 ID
      SiteVerificationTag = "UA-137248174-1"  # Google Search Console 인증 태그
      anonymizeIP = true  # IP 익명화
      respectDoNotTrack = true  # Do Not Track 헤더 존중
      useSessionStorage = false  # 세션 스토리지 사용 여부

  # 이미지 최적화 설정
  [params.cover]
    linkFullImages = true
    responsiveImages = true
    
  # 자산 최적화 설정
  [params.assets]
    disableHLJS = false
    disableScrollBarStyle = false
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"
    theme_color = "#b19cd9"

[params.header]
  enable = true

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats]
[outputFormats.JSON]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

# Google AdSense 설정 (Phase 3.3)
[params.adsense]
enabled = true  # 애드센스 활성화
client = "ca-pub-4944031426200690"  # 실제 AdSense 클라이언트 ID로 교체 필요
